### ISSUE TITLE
Allow running without bevy_render

### ISSUE THREAD

**Issue by mirsella** [merwaaan/bevy_spritesheet_animation#19] opened 2024-11-16 11:20 UTC
hello

im building a 2d multiplayer game, and for example i wanted to use this plugin's event to deal damage to a target at a certain frame.
my server would run in headless, without rendering or loading any texture, and so this plugin doesn't work currently without bevy_render because the 3d systems use `Res<Assets<Image>>`.

a feature flag, either `no_bevy_render`, or a `3d` enabled by default, to enable 3d sprites support.

a step further if you think it's good, would be a runtime config on the `SpritesheetAnimationPlugin` to enable or not the 3d sprites support. this is useful, to support on the same binary, headless and full game rendering. (server headfull, and server headless without render)
would be just a `3d: bool` field, enabled by default with a Default impl on the struct.

of course, i would be happy to do the PR if you accept these features. They shouldn't change the default behavior of this crate, but only allow it to be more flexible.

thanks

**Comment by merwaaan** [comment] 2024-11-16 13:00
That's an interesting use case, the suggested changes all sound good to me.

As you mentionned, the default configuration should enable 3D sprites so that everything work out of the box for the most common use cases.

Don't hesitate to make a PR.

**Comment by mirsella** [comment] 2024-11-16 13:05
ill do a pr soon !

what method do you prefer ? the feature flag or plugin option ?
the plugin option is more flexible: 
> this is useful, to support on the same binary headless and full game rendering

**Comment by merwaaan** [comment] 2024-11-17 11:46
I agree that the plugin option is better, we'll just release a new major version.

**Comment by mirsella** [comment] 2024-11-19 09:14
hey, even while disabling all three 3d systems and the 3d cache, i can't seems to make to plugin works without the SpritePlugin. do you have a idea why ?

i have replaced the &mut TextureAtlas in the querys to a Option, so that the plugin can work without bevy render (TextureAtlas are part of bevy render i learned).

There are no errors, but the play_frame method is only called once, at initialization i think.
with some logging i found that in Animator.update the animation_instance.accumulated_time is going up really slowly, like by 1 every few seconds, instead of going the normal speed (really fast)

**Comment by merwaaan** [comment] 2024-11-19 11:14
Mmh difficult to say what could be the cause. At first thought, your idea of replacing the TextureAtlas with an Option seems intuitive.

Have you found out why accumulated_time goes so slowly? Something wrong with Bevy's timer (shouldn't be dependent on the sprite plugin)? Or the sprite's speed factor?

**Comment by mirsella** [comment] 2024-11-19 16:58
I'll continue my search after work, I'll keep this thread updated !

**Comment by mirsella** [comment] 2024-11-19 18:33
yep its time related.
in the animator.update method, using minimalplugin the time.delta is ~190microseconds, while with defaultplugins its in the ~2.4ms.
ill try to find why

**Comment by mirsella** [comment] 2024-11-19 18:52
running the schedule slower fix it as expected:
```rs
            MinimalPlugins.set(ScheduleRunnerPlugin::run_loop(Duration::from_millis(
                1000 / 60,
            ))),
```
but i dont know why smaller values dont work, might be float imprecision ?

**Comment by mirsella** [comment] 2024-11-19 19:11
yep probably float imprecision or a wrong calculation :)
i have just replaced the u32 used internally by the duration type, and thanks to rust everything now works lol
lesson learned, always use the type made for it

**Comment by mirsella** [comment] 2024-11-19 19:13
yep probably float imprecision or a wrong calculation :)
i have just replaced the u32 used internally by the duration type, and thanks to rust everything now works lol
lesson learned, always use the type made for it

**Comment by mirsella** [comment] 2024-11-19 19:15
do i also replace the u32 by Duration in the 
```rs
pub enum AnimationDuration {
    PerFrame([u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html)),
    PerRepetition([u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html)),
}
``` type ?
This would further reduce the possibility of bugs by explicitly having to set which unit is it.
if this is too much which i understand, ill just put a doc comment saying in milliseconds

**Comment by mirsella** [comment] 2024-11-19 19:38
it even revealed a wrong test !

**Comment by merwaaan** [comment] 2024-11-20 11:45
Nice find!

I'd suggest not replaceing u32s in AnimationDuration with Durations.
(In an older version of the library, we used Duration but it made things more verbose without much added value since ms is a reasonnably standard unit for animations)

**Comment by merwaaan** [comment] 2024-11-20 11:49
#22 merged

**Closed by merwaaan** 2024-11-20 11:49 UTC

**Comment by mirsella** [comment] 2025-08-15 07:26
hey !)actually i think ill replace the 3d boolean option in the plugin by a enabled by default feature flag.
this allow not pulling in bevy_pbr if not using 3d. what do you think ?
